# ansible playbook to install and remove aur helper packages
 
 - name: remove octopi, and install pamac/yay
   hosts: local
   become: yes
   tasks:
   
     - name: full system upgrade "pacman -Syu"
       pacman:
         update_cache: yes
         upgrade: yes
       register: system_upgrade
       ignore_errors: True
     - debug: 
         var: system_upgrade.std_lines
       when: system_upgrade is failed
         
     - name: kill octopi and dependencies
       shell: pkill -f octopi
       register: kill_process
       ignore_errors: True
     - debug: 
         var: kill_process
       when: kill_process is failed
       
     - name: remove octopi package and dependencies
       pacman:
         name: "{{ item.name }}"
         state: absent
         force: yes
         recurse: yes         
       ignore_errors: True
       loop:
         - { name: 'octopi' }
         - { name: 'octopi-pacmanhelper' }
         - { name: 'octopi-repoeditor' }
         - { name: 'alpm-octopi-utils' }
         - { name: 'octopi-cachecleaner' }
         - { name: 'octopi-notifier-frameworks' }
       
     - name: install pamac and git packages
       pacman:
         name: "{{ item.name }}"
         state: present
       ignore_errors: True
       loop:
         - { name: pamac }
         - { name: git }
         - { name: base-devel }
         - { name: yay }
         
     - name: clone the ansible-aur repository
       become: yes
       git:
         repo: https://github.com/kewlfft/ansible-aur.git
         dest: /usr/share/ansible/plugins/modules
         update: no
       register: cloned
       ignore_errors: True
     - debug:
         var: cloned
       when: cloned is failed
