# install/remove software
 
 - name: install/remove official repository packages
   hosts: local
   become: yes
   tasks:  
   
     - name: full system upgrade "pacman -Syu"
       pacman:
         update_cache: yes
         upgrade: yes
       register: system_upgrade
       ignore_errors: True
     - debug: 
         var: system_upgrade
       when: system_upgrade is failed   
   
     - name: install packages 
       pacman:
         name: "{{ item.name }}"
         state: present
       ignore_errors: True
       loop:
         # web
         - { name: 'chromium' }
         - { name: 'transmission-gtk' }
         - { name: 'gufw' }
         - { name: 'ufw' }
         - { name: 'kodi' }         
         # text editors
         - { name: 'gimp' }
         - { name: 'gedit' }
         # programmin
         - { name: 'python' }
         - { name: 'python-flask' } 
         - { name: 'python-flask-migrate' }
         - { name: 'python-flask-marshmallow' }
         - { name: 'python-flask-restful' }
         - { name: 'python-flask-wtf' }
         - { name: 'python-sqlalchemy' }
         - { name: 'python-django' }
         - { name: 'python-matplotlib' }
         - { name: 'python-numpy' }
         - { name: 'python-pandas' }
         - { name: 'jupyter-notebook' }
         # virtualization
         - { name: 'qemu' }
         - { name: 'qemu-arch-extra' }
         - { name: 'qemu-block-gluster' }
         - { name: 'qemu-block-iscsi' }
         - { name: 'qemu-block-rbd' }
         - { name: 'samba' }
         - { name: 'libvirt' }
         # system configuration
         - { name: 'etckeeper' }
         - { name: 'ansible' }
         - { name: 'etcher' }
         - { name: 'android-tools' }
         - { name: 'java-openjfx' }
         - { name: 'redshift' }
         - { name: 'plasma5-applets-redshift-control' }
         # themes
         - { name: 'papirus-icon-theme' }
         - { name: 'paper-icon-theme-git' }
         - { name: 'numix-gtk-theme' }
         - { name: 'numix-manjaro-themes' }
         - { name: 'gtk-engine-murrine' }
         
     - name: remove packages
       pacman:
         name: "{{ item.name }}"
         state: absent
         recurse: yes
         force: yes
       ignore_errors: True
       loop:
         - { name: 'python-pip'}
         - { name: 'qbittorrent' }  
