# Eexcute shell command to kill a process and its dependencies if the process is running
- hosts: local
  vars:
    process_name: '' 
  tasks:
  - name: kill process and dependencies
    shell: pkill -f {{ process_name }}
    register: result
  - debug:
      var: result

# To test, open an application and record it's [process_name], 
# then run the following command
# ansible-playbook roles/common/tasks/kill_process.yaml --extra-vars 'process=[process_name]'
