# Use the pacman module to upgrade the system
- hosts: local
  tasks:
    - name: Run the equivalent of "pacman -Syu" as a separate step
      pacman:
        update_cache: yes
        upgrade: yes
      register: result
    - debug:
        var: result
