# Use the pacman module to upgrade the system
- hosts: local
  tasks:
    - name: upgrade all packages
      become: yes
      pacman:
        update_cache: yes
        upgrade: yes
      register: result
      ignore_errors: True
    - debug:
        var: result
      when: result is failed
